version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - POSTGRES_PASSWORD
      - ASANA_TOKEN