# Generated by Django 2.2.11 on 2020-03-22 20:07

import app.asana_api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('gid', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.asana_api.WithAPI),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('gid', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.asana_api.WithAPI),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('gid', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assignee')),
                ('projects', models.ManyToManyField(blank=True, to='app.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.asana_api.WithAPI),
        ),
    ]
