# Generated by Django 2.2.11 on 2020-03-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gid',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
