# Generated by Django 2.2.11 on 2020-03-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
